# -*- coding: utf-8 -*-
# Copyright 2021 Red Hat
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, division, print_function

__metaclass__ = type

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the
# cli_rm_builder.
#
# Manually editing this file is not advised.
#
# To update the argspec make the desired changes
# in the module docstring and re-run
# cli_rm_builder.
#
#############################################

"""
The arg spec for the vyos_firewall_zones module
"""


class Firewall_zonesArgs(object):  # pylint: disable=R0903
    """The arg spec for the vyos_firewall_zones module
    """

    def __init__(self, **kwargs):
        pass

    argument_spec = {
        "config": {
            "type": "list",
            "elements": "dict",
            "options": {
                "name": {"type": "str", "required": True},
                "default_action": {"type": "str", "choices": ["drop", "reject"]},
                "description": {"type": "str"},
                "from": {
                    "type": "list",
                    "elements": "dict",
                    "options": {
                        "from_zone": {"type": "str", "required": True},
                        "afi": {
                            "type": "str",
                            "required": True,
                            "choices": ["ipv4", "ipv6"],
                        },
                        "rule_set_name": {"type": "str", "required": True},
                        },
                    },
                },
                "interfaces": {
                    "type": "list",
                    "options": {"name": {"type": "str", "required": True}},
                },
                "local_zone": {"type": "bool"},
            },

        "state": {
            "type": "str",
            "choices": [
                "merged",
                "replaced",
                "overridden",
                "deleted",
                "gathered",
                "rendered",
                "parsed",
            ],
            "default": "merged",
        },
    }  # pylint: disable=C0301
